### ISSUE TITLE
[BUG] node_exporter doesn't take --config.file flag

### ISSUE THREAD

**Issue by viq** [saltstack-formulas/prometheus-formula#23]
### Formula commit hash / release tag
d9c93860385303ae89025431da7a83d48c5a6adf

### Versions reports (master & minion)
```
salt-call --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 3.5.2 (default, Oct  8 2019, 13:06:37)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1092-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

### Pillar / config used
```
prometheus:
  tofs:
    source_files:
      prometheus-archive-install-node_exporter-managed-service:
        - node_exporter.service.jinja
  wanted:
    - prometheus
    - node_exporter
    - alertmanager
  use_upstream_archive: True
  pkg:
    prometheus:
      archive_version: '2.14.0'
      archive_hash: ddf47223ec716594254df110ee26ad52e66d7d4471ae8edbf9020087396861e5
    node_exporter:
      archive_version: '0.18.1'
      archive_hash: b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424
      name: node_exporter
      args_file: /etc/default/node_exporter
    alertmanager:
      archive_version: '0.19.0'
      archive_hash: 6191788f8b91a05955fcdc2ab4bc7d0edf70e5039f3acffb284d75745cc80d67
  service:
    prometheus:
      args:
        web.listen-address: "127.0.0.1:9090"
    node_exporter:
      args:
        web.listen-address: "127.0.0.1:9100"
  config:
    prometheus:
      global:
        scrape_interval: 10s
        evaluation_interval: 10s
      alerting:
        alertmanagers:
          - static_configs:
            - targets:
              - localhost:9093
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node'
          static_configs:
            - targets: ['localhost:9100']
```

---

### Describe the bug
```
Dec 11 22:22:02 ip-172-31-29-172 node_exporter[2832]: node_exporter: error: unknown long flag '--config.file', try --help
```
`node_exporter` doesn't take the `--config.file` flag, yet there's no way to skip it, looking at https://github.com/saltstack-formulas/prometheus-formula/blob/bb94cbc606c8d5b95c1078a54c73a1287ac1ccee/prometheus/archive/install.sls#L61-L62
I'm trying to make it use a different file using the `TOFS` pattern, but I wasn't able to find the correct incantation yet.

### Steps to reproduce the bug
Try to run `node_exporter` version `0.18.1` with current formula

### Expected behaviour
`node_exporter` is able to run

### Attempts to fix the bug
Currently for least impact I'm trying to make the service use a different file, but probably a better idea would be to add a conditional to the service, or add a way to define the start command in pillars.
