### ISSUE TITLE
[BUG] Setup without firewalld results with salt failing further communication

### ISSUE THREAD

**Issue by beamerkun** [saltstack-formulas/prometheus-formula#33]
### Formula commit hash / release tag
68f54e4dad0f14a4431ff12d6da981f6ea151575

### Versions reports (master & minion)
master:
```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Jul 20 2020, 15:37:01)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-50-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
minion:
```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Apr 15 2020, 17:20:14)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-96-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### Pillar / config used
```
prometheus:
  pkg:
    use_upstream_archive: true
    use_upstream_repo: false
    component:
      prometheus:
        service:
          args:
            web.listen_address: <redatcted>:9090
        config:
          scrape_configs:
          - job_name: <redatcted>
            scrape_interval: 5s
            static_configs:
              - targets: ['<redatcted>']
          - job_name: 'prometheus_host'
            static_configs:
              - targets: ['localhost:9090']
          - job_name: <redatcted>
            metrics_path: '/plugins/metrics-reporter-prometheus/metrics'
            scheme: https
            static_configs:
              - targets: ['<redatcted>', '<redatcted>']
```
---

### Describe the bug

After running `salt <my-host> state.apply`, further attempts to connect using Salt end up with:
```
<my-host>:
    Minion did not return. [No response]
```

Problem is that I do not use any firewalling in my setup (we're in internal network already). This formula forces installation of `firewalld` - and with defaults/adapted settings from example pillars, I end up with non-functional service and no way to recover using saltstack.

### Expected behaviour

- Settings that allows to disable using `firewalld`, preferably `false` by default
-or-
- Make sure default firewall settings do not block SaltStack from communicating with minion

### Attempts to fix the bug
- Adding following pillar did not help:
```
wanted:
  firewall: false
```
