### ISSUE TITLE
[BUG] All possibilities cannot be expressed

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/prometheus-formula#35]
### Pillar / config used

---

### Describe the bug

When installing `prometheus-node-exporter` from Debian repo the service is called `prometheus-node-exporter`
When installing `prometheus-node-exporter` from archives the service is called `node_exporter`

This distinction cannot be made in the conf :

```yml
---
Debian:
  pkg:
    node_exporter:
      name: prometheus-node-exporter
      args_file: /etc/default/prometheus-node-exporter
    alertmanager:
      name: prometheus-alertmanager
  service:
    node_exporter:
      name: prometheus-node-exporter
    alertmanager:
      name: prometheus-alertmanager
```

The issue comes from the fact that `pkg` hash holds everything about packages config.

It contains info for the system package repository and may be used to configure the `archive.sls` state.

The result is you cannot mix both system in your infrastructure : you can't have nodes with `node_exporter` coming from the repo and other nodes with `node_exporter` coming from the archives.
