### ISSUE TITLE
[BUG] service.args is only compatible with FreeBSD

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/prometheus-formula#36]
### Pillar / config used

---

### Describe the bug

Since there is no `else` in [service/args/install.sls](https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/service/args/install.sls#L34) it breaks.

```yml
       ----------
                 ID: prometheus-service-running-node_exporter
           Function: service.running
               Name: node_exporter
             Result: False
            Comment: The following requisites were not found:
                                 require:
                                     sls: prometheus.service.args.install
            Started: 19:36:01.252119
           Duration: 0.006 ms
            Changes:   
       ----------
                 ID: prometheus-service-running-node_exporter
           Function: service.running
               Name: firewalld
             Result: False
            Comment: The following requisites were not found:
                                 require:
                                     sls: prometheus.service.args.install

```
