### ISSUE TITLE
[BUG] Cannot install only node_exporter

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/prometheus-formula#37]
### Pillar / config used

---

### Describe the bug

It fails with 

```yml
       ----------
                 ID: prometheus-archive-install-prerequisites
           Function: file.directory
               Name: /var/lib/prometheus
             Result: False
            Comment: User prometheus is not available Group prometheus is not available
            Started: 19:23:19.133033
           Duration: 2.279 ms
            Changes:   
       ----------
                 ID: prometheus-archive-install-node_exporter
           Function: file.directory
               Name: /opt/prometheus/node_exporter-v0.18.1
             Result: False
            Comment: One or more requisite failed: prometheus.archive.install.prometheus-archive-install-prerequisites
            Started: 19:23:19.135989
           Duration: 0.006 ms
            Changes: 
```

because of https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/archive/install.sls#L16
