### ISSUE TITLE
[BUG] pkg.component.prometheus.service.args arguments is not working

### ISSUE THREAD

**Issue by MurzNN** [saltstack-formulas/prometheus-formula#61]
### Formula commit hash / release tag
56d444b8133d04a53d38c42be3de78c2724de3e92c00ee99450d7c18c7f05011

### Versions reports (master & minion)
```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.14.2
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 4.1.0
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, May 27 2021, 13:30:53)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-72-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

### Pillar / config used
```yaml
prometheus:
  pkg:
    use_upstream_repo: true
    use_upstream_archive: false
    component:
      prometheus:
        service:
          args:
            web.listen-address: 192.168.1.1:9191
            enable-feature: remote-write-receiver
```

### Describe the bug
I trying to enable remote write receiver, and set custom listen address and port. I took example from pillar.example and fill needed values, applied changes without errors, but as result - my config is not applied.

Changes to other part of pillar, for example, `scrape_interval: 16s`, applied successfully.

### Steps to reproduce the bug
1. Add to the pillar in section `pkg.component.prometheus.service.args` some args, eg:
```yaml
          args:
            web.listen-address: 192.168.1.1:9191
            enable-feature: remote-write-receiver
```
2. Apply changes via `state.apply`
3. See that `prometheus` process don't receive this arguments.
File `/lib/systemd/system/prometheus.service` also don't contain my custom args.

### Expected behaviour

Custom args must be applied via adding to `/lib/systemd/system/prometheus.service` file or via some other way.

**Comment by MurzNN** [comment]
Thanks, I saw that issue, but it is for environment  variables, but my - for arguments, but if the solution is same - that's good!

**Comment by B1ue-W01f** [comment]
Yeah prometheus can have these config options passed into the service file or the environ file. Previously it was partially implemented, but ultimately not working for either.

When the pull request is complete, this will work through the environ piller in the same format as you gave above, i.e.:

```
prometheus:
  pkg:
    use_upstream_repo: true
    use_upstream_archive: false
    component:
      prometheus:
        environ:
          args:
            web.listen-address: 192.168.1.1:9191
            enable-feature: remote-write-receiver
```

Im based off the repo my pull is from and the above pillar deploys the correct config.

**Comment by MurzNN** [comment]
I updated to v5.5.1, but this still not working, here is my part of the pillar:
```
      prometheus:
        version: v2.28.0
        archive:
          source_hash: d2d0ded275090a13208114b633abe41c40e14c83ff5ec07230d79b4da1d8e701
        service:
          args:
            web.listen-address: localhost:9091
            enable-feature: remote-write-receiver
        environ:
          args:
            web.listen-address: localhost:9092
            enable-feature: remote-write-receiver2
```
