### ISSUE TITLE
[BUG] Archive Install process not idempotent (systemctl daemon-reload)

### ISSUE THREAD

**Issue by mdschmitt** [saltstack-formulas/prometheus-formula#68]
### Formula commit hash / release tag
v5.5.1

### Versions reports (master & minion)
```
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.7.2
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.6.1
        Python: 3.7.10 (default, Jun  3 2021, 00:02:01)
  python-gnupg: Not Installed
        PyYAML: 4.2
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: amzn 2
        locale: UTF-8
       machine: x86_64
       release: 4.14.232-177.418.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2
```

### Pillar / config used
```yaml
---
prometheus:
  wanted:
    component:
      - node_exporter
  exporters:
    node_exporter:
      textfile_collectors_dependencies: []
      textfile_collectors: {}
  pkg:
    use_upstream_archive: true
    component:
      node_exporter:
        version: v1.1.2
        archive:
          source_hash: 8c1f6a317457a658e0ae68ad710f6b4098db2cad10204649b51e3c043aa3e70d
        commands:
          - node_exporter
        service:
          args:
            collector.systemd: null
            collector.ntp: null
            collector.ntp.server-is-local: null
            web.listen-address: ":9100"
```

---

## Bug details
Archive Install runs "systemctl daemon-reload" regardless of whether or not the archive install's systemd service script is correctly populated already.
https://github.com/saltstack-formulas/prometheus-formula/blob/v5.5.1/prometheus/archive/install.sls#L154

### Steps to reproduce the bug
`salt '*' state.sls prometheus && salt '*' state.sls prometheus` (using the above pillar values)

### Expected behaviour
`changed=0` output in second Salt run

### Attempts to fix the bug
n/a.
