### ISSUE TITLE
[BUG] Feature flag does not seem to be passed to the service

### ISSUE THREAD

**Issue by gabrielSoudry** [saltstack-formulas/prometheus-formula#75]
### Formula commit hash / release tag
Master 92ab8cdf332f264b8954a682e2b4e32b258bc54c

### Versions reports (master & minion)

salt-call --versions-report
Salt Version:
          Salt: 3004

### Pillar / config used
```
prometheus:
  wanted:
    component:
      - node_exporter
      - prometheus
  exporters:
    node_exporter:
      textfile_collectors_dependencies: []
      textfile_collectors: {}
  pkg:
    use_upstream_archive: true
    component:
      node_exporter:
        version: v1.3.1
        archive:
          source_hash: 68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949 
        commands:
          - node_exporter
        service:
          args:
            collector.systemd: null
            collector.ntp: null
            collector.ntp.server-is-local: null
            web.listen-address: ":9300"
      prometheus:
        service:
          args:
            web.listen-address: 0.0.0.0:9090
            enable-feature: 'agent'
        version: v2.33.1
        archive:
          source_hash: 55de29727fc4d3977d3400c54fa222ebb52755bd0201936f1e1052fea6f2b44b
        config:
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'node_exporter'
              scrape_interval: 5s
              honor_labels: true
              static_configs:
                - targets: ['pushgateway:9300']

```
 Same as https://github.com/saltstack-formulas/prometheus-formula/pull/74, I want to enable agent mode in the service  but I have : 
```
 prometheus.service - prometheus - prometheus service
     Loaded: loaded (/lib/systemd/system/prometheus.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-10 15:17:30 CET; 4min 59s ago
       Docs: https://github.com/saltstack-formulas/prometheus-formula
   Main PID: 1050513 (prometheus)
      Tasks: 13 (limit: 18772)
     Memory: 31.7M
     CGroup: /system.slice/prometheus.service
             └─1050513 /opt/prometheus/prometheus-v2.33.1/prometheus --config.file=/etc/prometheus/prometheus.yml

```

Instead of :

```
prometheus.service - prometheus - prometheus service
     Loaded: loaded (/lib/systemd/system/prometheus.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-10 15:17:30 CET; 4min 59s ago
       Docs: https://github.com/saltstack-formulas/prometheus-formula
   Main PID: 1050513 (prometheus)
      Tasks: 13 (limit: 18772)
     Memory: 31.7M
     CGroup: /system.slice/prometheus.service
             └─1050513 /opt/prometheus/prometheus-v2.33.1/prometheus --config.file=/etc/prometheus/prometheus.yml --enable-feature=agent 
```

I am really new in salt, I apologize in advance if my configuration is bad
