### ISSUE TITLE
[BUG] Broken Idempotency for RPM pkgrepo definitions

### ISSUE THREAD

**Issue by mdschmitt** [saltstack-formulas/prometheus-formula#76]
### Formula commit hash / release tag

v5.6.2

### Versions reports (master & minion)

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.7.1
        Python: 3.7.10 (default, Jun  3 2021, 00:02:01)
  python-gnupg: Not Installed
        PyYAML: 4.2
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: amzn 2
        locale: UTF-8
       machine: x86_64
       release: 4.14.232-177.418.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2
```

### Pillar / config used

```yaml
prometheus:
  wanted:
    component:
      - node_exporter

  pkg:
    use_upstream_repo: true
```

---

### Describe the bug

[prometheus/package/repo/install.sls](https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/package/repo/install.sls#L11) actually isn't idempotent due to the `file.replace` in the pkgrepo.managed block for setting up the repo.  I've only tested this on AmazonLinux 2, but afaik, it applies to all other yum-based systems as well.

Basically, "why are we using this `gpgkey2` replacement thing at all?"  If you specify the whole line with space-separated key URLs, yum is able to handle all the keys just fine.

### Steps to reproduce the bug

Do a salt MINION state.test prometheus with the above pillar vals set.

At least on Amazon Linux 2 (pretty much analogous to CentOS 7), it does a pkgrepo.managed to try to make the repo, then a file.replace on that created resource every time the formula is run.  Broken idempotency.

### Expected behaviour

Idempotent executions _and_ successful yum installs with gpgkey-validated package pull/installation.

### Attempts to fix the bug

Workaround to essentially skip the `file.replace` is just to override that gpgkey key with a pillar value like this:
```yaml
---
# Manage prometheus exporters (handled by the prometheus formula)
prometheus:
  wanted:
    component:
      - node_exporter
  pkg:
    use_upstream_repo: true
    repo:
      gpgkey: 'https://packagecloud.io/prometheus-rpm/release/gpgkey https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm'
```

This fixes idempotency afaict.  🤷
